### ISSUE TITLE
Atualizar header.html, index.html

### ISSUE THREAD

**Issue by paullomarttins** [paullomarttins/lembre-me#4]
**Hi, @tha-is !**

Fiz algumas inclusões no novo template header.html e no index.html.

1. header.html - não inclui os parâmetros de CSS/JS para ajustar o front-end.
2. index.html - foi incluído o paginador mas sem parâmetros de CSS/JS para o front-end.

**Comment by tha-is** [comment]
Hi, @paullomarttins!

- [ x ] header.html - não inclui os parâmetros de CSS/JS para ajustar o front-end.
## Nav personalizada.

- [ x ] index.html - foi incluído o paginador mas sem parâmetros de CSS/JS para o front-end.
## Ajustes de flexibilização da paginação e personalização do conteudo.
